name: Basic build test

on: push
jobs:
  Build_Project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./gradlew build
  Generate_Javadoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./gradlew javadoc
      - name: Deploy to gh-pages
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: build/html
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
