name: Basic build test

on: push
jobs:
  Build_Project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: javac *.java
  Run_Basic_IO_Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: javac *.java
      - run: java Main < test1.txt > test1_generated.txt
      - run: diff test1_generated.txt test1_expected.txt
      - run: java Main < test2.txt > test2_generated.txt
      - run: diff test2_generated.txt test2_expected.txt
